services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - /home/aavduli/data/wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/aavduli/data/wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - /home/aavduli/data/mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    name: wordpress_data
  mariadb:
    name: mariadb_data

networks:
  inception:
    name: inception
